version: 2.1
defaults: &defaults
  docker:
    - image: circleci/node:14.15.3
  parallelism: 1
  working_directory: /tmp/front-office
  environment:
    TZ: "/usr/share/zoneinfo/Asia/Tokyo"

jobs:
  build:
    <<: *defaults

    steps:
      - checkout

      - restore_cache:
          keys:
          - dependencies-{{ .Environment.CACHE_VERSION }}-{{ checksum "package-lock.json" }}-node1
          - dependencies-{{ .Environment.CACHE_VERSION }}-node

      - run:
          name: npm Install
          command: npm ci

      - save_cache:
          key: dependencies-{{ .Environment.CACHE_VERSION }}-{{ checksum "package-lock.json" }}-node1
          paths:
            - ~/.npm
            - node_modules

      # Audit
      - run:
          name: Node Packages Audit
          command: npm run ci:audit

      # save the node_module folder to be reusable in the other jobs
      - persist_to_workspace:
          root: .
          paths:
            - node_modules

  deploy:
    <<: *defaults
    steps:
      - checkout
      - attach_workspace:
          # Must be absolute path or relative path from working_directory
          at: /tmp/front-office

      # Deploy to Firebase
      - deploy:
          name: Deploy branch to matching firebase app
          command: |
            echo "deploying branch ${CIRCLE_BRANCH}"
            DEPLOY_BRANCH=$CIRCLE_BRANCH npm run deploy

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build:
          filters:
            tags:
              only: /.*/
      - deploy:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - demo
                - production
                - /qa[\d]+/
